export const ROUTE_NAMES = {
  LOAD: "/",
  HOME: "/home",
  SETTINGS: "/settings",
  SETTINGS_LANGUAGE: "/settings/language",
  SETTINGS_CURRENCY: "/settings/currency",
  HISTORY: "/history",
  RECEIVE: "/receive",
  SEND: "/send",
  SEND_SELECT: "/send/select",
  SEND_SUCCESS: "/send/success",
  SEND_NFT: "/nft/:address/send",
  SEND_NFT_SUCCESS: "/nft/send/success",
  SELL_NFT: "/nft/:address/sell",
  SELL_NFT_SELECTCURRENCY: "/nft/:address/sell/selectCurrency",
  SELL_NFT_SUCCESS: "/nft/sell/success",
  MENU: "/menu",
  MENU_EXPANDED: "/menuexpanded",
  BUY_TON: "/purchaseTon",
  FIAT_SELECT: "/pTonSelectFiat",
  BUY_TON_STEP1: "/pTonStep1",
  NFT: "/nft",
  NFT_DETAIL: "/nft/:address",
  SWAP: "/swap",
  SWAP_SELECT: "/swap/select",
  SWAP_SUCCESS: "/swap/success",
};
