export const ROUTE_NAMES = {
  LOAD: "/",
  HOME: "/home",
  SETTINGS: "/settings",
  HISTORY: "/history",
  RECEIVE: "/receive",
  SEND: "/send",
  SEND_SELECT: "/send/select",
  SEND_SUCCESS: "/send/success",
  MENU: "/menu",
  MENU_EXPANDED: "/menuexpanded",
  BUY_TON: "/purchaseTon",
  FIAT_SELECT: "/pTonSelectFiat",
  BUY_TON_STEP1: "/pTonStep1",
  NFT: "/nft",
  SWAP: "/swap",
  SWAP_SELECT: "/swap/select",
};
